Repository spryker/uuid-behavior, pull requests merged in 2018-08, with the labels that each got.

#4 GLUE-165: Uuid behavior
  .coveralls.yml
  .gitattributes
  .gitignore
  .travis.yml
  CHANGELOG.md
  LICENSE
  codeception.yml
  composer.json
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/Exception/ColumnNotFoundException.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/Exception/InvalidParameterValueException.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/Exception/MissingAttributeException.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/UuidBehavior.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectBaseAttribute.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectGetUuidGeneratorService.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectSetGeneratedUuid.php
  src/Spryker/Zed/UuidBehavior/UuidBehaviorConfig.php
  src/Spryker/Zed/UuidBehavior/UuidBehaviorDependencyProvider.php
  tests/SprykerTest/Zed/UuidBehavior/Persistence/Propel/Behavior/UuidBehaviorTest.php
  tests/SprykerTest/Zed/UuidBehavior/codeception.yml
Labels: feature, request-for-review

#6 Fix CS.
  .travis.yml
  phpstan.json
  phpstan.neon
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectBaseAttribute.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectGetUuidGeneratorService.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectSetGeneratedUuid.php
Labels: merge-only

#5 [BUGFIX] GLUE-764 Wrong uuid "cart" behavior when adding an item to cart
  composer.json
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/Exception/MissingAttributeException.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/UuidBehavior.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectGetUuidGeneratorService.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectSetGeneratedUuid.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectUpdateUuidAfterInsert.php
  src/Spryker/Zed/UuidBehavior/Persistence/Propel/Behavior/templates/objectUpdateUuidBeforeUpdate.php
  tests/SprykerTest/Zed/UuidBehavior/Persistence/Propel/Behavior/UuidBehaviorTest.php
Labels: bug, ready-for-release
